### ISSUE TITLE
Releasing this package

### ISSUE THREAD

**Issue by ijnek** [dynamixel-community/dynamixel_hardware#29]
Hi @youtalk , thanks for developing and maintaining this package. I remember at ROSCon JP (I was there), you mentioned some things preventing you releasing this package.

I'd like to know what the roadblockers currently are, prevnting this package from being released into ROS 2? The obvious one I can think of is [ROBOTIS-GIT/dynamixel-workbench](https://github.com/ROBOTIS-GIT/dynamixel-workbench) missing releases for ROS2. Are there any others?

**Comment by youtalk** [comment]
Thank you for your recent effort to this repository.

> The obvious one I can think of is [ROBOTIS-GIT/dynamixel-workbench](https://github.com/ROBOTIS-GIT/dynamixel-workbench) missing releases for ROS2.

This is the truth. That is why I cannot release it.

**Comment by ijnek** [comment]
Ok, I've opened https://github.com/ROBOTIS-GIT/dynamixel-workbench/issues/361 to request dynamixel-workbench to be released for ROS 2.
